#!/usr/bin/with-contenv sh

USER_ID=${DASPANEL_SYS_USERID:-1000}
echo "Starting with UID : $USER_ID"
addgroup -g $USER_ID daspanel
adduser -s /bin/false -D -h /home/daspanel -u $USER_ID -G daspanel daspanel

# Installation UUID must be informed
if [ -z "$DASPANEL_GUUID" ]; then
    echo "***"
    echo "ERROR: You must set the env variable DASPANEL_GUUID to a valid UUID"
    echo "***"
    exit 1
fi

# unless this has already been defined, set
if [ -z "$DASPANEL_HOST" ]; then
    export DASPANEL_HOST="daspanel.site"
    printf $DASPANEL_HOST > /var/run/s6/container_environment/DASPANEL_HOST
    echo "DASPANEL_HOST = $DASPANEL_HOST"
fi

# unless this has already been defined, set
if [ -z "$DASPANEL_MASTER_EMAIL" ]; then
    export DASPANEL_MASTER_EMAIL="admin@$DASPANEL_HOST"
    printf $DASPANEL_MASTER_EMAIL > /var/run/s6/container_environment/DASPANEL_MASTER_EMAIL
    echo "DASPANEL_MASTER_EMAIL = $DASPANEL_MASTER_EMAIL"
fi

# unless this has already been defined, set
if [ -z "$DASPANEL_MASTER_PASSWORD" ]; then
    export DASPANEL_MASTER_PASSWORD=`date +%s | sha256sum | base64 | head -c 16 ; echo`
    printf $DASPANEL_MASTER_PASSWORD > /var/run/s6/container_environment/DASPANEL_MASTER_PASSWORD
    echo "DASPANEL_MASTER_PASSWORD = $DASPANEL_MASTER_PASSWORD"
fi

# unless this has already been defined, set
if [ -z "$DASPANEL_MSG_HUB" ]; then
    export DASPANEL_MSG_HUB="mail-catcher"
    printf $DASPANEL_MSG_HUB > /var/run/s6/container_environment/DASPANEL_MSG_HUB
    echo "DASPANEL_MSG_HUB = $DASPANEL_MSG_HUB"
fi

if [ ! -d "/opt/daspanel/data/$DASPANEL_GUUID" ]; then
	mkdir -p "/opt/daspanel/data/$DASPANEL_GUUID"
fi

if [ ! -d "/opt/daspanel/data/$DASPANEL_GUUID/db" ]; then
	mkdir -p "/opt/daspanel/data/$DASPANEL_GUUID/db"
fi

if [ ! -d "/opt/daspanel/log/$DASPANEL_GUUID" ]; then
	mkdir -p "/opt/daspanel/log/$DASPANEL_GUUID"
fi

# Create config if not exists
if [ ! -f /opt/daspanel/data/$DASPANEL_GUUID/db/sysconfig.json ]; then
    CFG_JSON=$(jq -n -c -M \
        '{
            "SYS": {
                "DASPANEL_MASTER_EMAIL": env.DASPANEL_MASTER_EMAIL,
                "DASPANEL_MASTER_PASSWORD": env.DASPANEL_MASTER_PASSWORD,
                "DASPANEL_HOST": env.DASPANEL_HOST,
                "DASPANEL_MSG_HUB": env.DASPANEL_MSG_HUB
            },
            "SMTP": {
                "type": "mail-catcher",
                "server": "daspanel-mail-catcher:1025",
                "user": env.DASPANEL_MASTER_EMAIL,
                "password": env.DASPANEL_GUUID
            }
        }' \
    )
    printf $CFG_JSON > /opt/daspanel/data/$DASPANEL_GUUID/db/sysconfig.json
else
    # Update configuration
    cfg_source=$(cat /opt/daspanel/data/$DASPANEL_GUUID/db/sysconfig.json)
    echo $cfg_source | \
    jq -cM '.SYS.DASPANEL_MASTER_EMAIL="'$DASPANEL_MASTER_EMAIL'"' | \
    jq -cM '.SYS.DASPANEL_MASTER_PASSWORD="'$DASPANEL_MASTER_PASSWORD'"' | \
    jq -cM '.SYS.DASPANEL_HOST="'$DASPANEL_HOST'"' | \
    jq -cM '.SYS.DASPANEL_MSG_HUB="'$DASPANEL_MSG_HUB'"' | \
    jq -cM '.SMTP.user="'$DASPANEL_MASTER_EMAIL'"' > /opt/daspanel/data/$DASPANEL_GUUID/db/sysconfig.json
fi

# secure daspanel
chown -R daspanel:daspanel /opt/daspanel/data
chown -R daspanel:daspanel /opt/daspanel/log

