#!/usr/bin/with-contenv sh

# Installation UUID must be informed
if [ -z "$DASPANEL_SYS_UUID" ]; then
    echo "***"
    echo "ERROR: You must set the env variable DASPANEL_SYS_UUID to a valid UUID"
    echo "***"
    exit 1
fi

# Configure
/usr/bin/gomplate -d cfg=file:///opt/daspanel/data/$DASPANEL_SYS_UUID/db/sysconfig.json \
    < /opt/daspanel/conf-templates/etc/ssmtp/mailhog-ssmtp.conf.tmpl \
    >  /etc/ssmtp/ssmtp.conf

/usr/bin/gomplate -d cfg=file:///opt/daspanel/data/$DASPANEL_SYS_UUID/db/sysconfig.json \
    < /opt/daspanel/conf-templates/etc/ssmtp/revaliases.tmpl \
    >  /etc/ssmtp/revaliases

# secure ssmtp - https://wiki.archlinux.org/index.php/SSMTP
addgroup ssmtp
chown :ssmtp /etc/ssmtp/ssmtp.conf
chown :ssmtp /usr/sbin/ssmtp
chmod g+s /usr/sbin/ssmtp

